### ISSUE TITLE
What's the proper way to register this plugin?

### ISSUE THREAD

**Issue by rowild** [ljovcheg/konva-gsap3-plugin#1]
Thank you for your efforts to provide s gsap3 plugin! Awesome! Would love to try it, but I fail registering it. Could you probably update the docu with a `gsap.registerPlugin(...)` example? That would really help!
It would also be very helpful, if you could add an example on how to use this plugin on codepen, e.g. (or an other online code editor).

**Comment by ljovcheg** [comment]
Check out this sample https://codepen.io/plur/pen/yLPoQPm
I've minified the same script from konva_gsap3_plugin.js.

You don't need to register plugin as it will register itself when you add it to your project.

**Comment by rowild** [comment]
Thank you, @ljovcheg !
